### ISSUE TITLE
Option to have badges in front of the text

### ISSUE THREAD

**Issue by marceloverdijk** [HiDeoo/starlight-openapi#105]
### Is your feature request related to a problem?

I would be nice to have the option for the [badges](https://starlight-openapi.vercel.app/configuration/#badges) (GET, POST, PUT, DELETE) to be in front of the label instead of behind the label.

### Describe the solution you'd like

E.g.

__GET__ List of persons

instead of

List of persons __GET__

in generated operation labels in sidebar.

**Comment by HiDeoo** [comment]
Thanks for the feedback.

Badges are built on top of the [existing Starlight feature](https://starlight.astro.build/guides/sidebar/#badges) which does not support different positions for badges. However, you can use [custom CSS](https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles) to position the badges as needed:

```css
.sidebar-content a:has(.sl-badge) {
  display: flex;
  flex-direction: row-reverse;
  align-items: center;
  justify-content: start;
  gap: 0.5rem;
}
```

Which would render like this:

<img width="280" alt="Image" src="https://github.com/user-attachments/assets/3fb27b47-1385-4d5b-bcfc-96e3b8ec653e" />

Also, a [feature request](https://github.com/withastro/starlight/discussions/new?category=feature-requests) could be opened in the Starlight repository to measure interest in such option if you think it would be useful for others as well.
