### ISSUE TITLE
[Feature Request] Support interpreting style: form and explode: false for arrays

### ISSUE THREAD

**Issue by taiseimiyaji** [HiDeoo/starlight-openapi#69]
### Is your feature request related to a problem?

I would like the documentation tool to automatically display examples in a comma-separated format when a parameter is defined with `style: form` and `explode: false`. For instance, if an array parameter `ids` is set this way, the tool should generate an example request like `?ids=1,2,3`, ensuring consistency with the OpenAPI 3.x specification for this serialization style.  

Currently, the way examples are displayed can be a bit unclear, making it harder for users to immediately grasp the correct format. Adjusting this behavior would improve clarity and usability.

This issue is particularly problematic for GET query parameters.

### Describe the solution you'd like

I would like the documentation tool to detect when a parameter is defined with `style: form` and `explode: false` and automatically display the example as comma-separated. For instance, if I define an array parameter `ids` this way, the tool should show an example request like `?ids=1,2,3`, matching the OpenAPI 3.x specification for this serialization style.

### Describe alternatives you've considered

1. Manually overriding the example for each parameter to show `1,2,3`. However, this is tedious and prone to errors.
2. Adding a note in the description field explaining that arrays should be sent comma-separated. But this still isn't as clear or automatic as having the tool generate the correct format itself.
3. Using a different serialization style (`explode: true`) or separate query parameters for each array element, but that doesn't meet our requirements for comma-separated values.

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands: 

Will you be able to provide a small example schema showing the use case, how the examples are specified in this schema, etc. so that I can make sure to capture the exact context?

**Comment by taiseimiyaji** [comment]
Of course😀  

Below is a simple example of a schema👀

```yaml
get:
  ~~ Omitted ~~
  parameters:
    - name: resource_id
      in: query
      description: |-
        resourceID(Multiple specifications can be separated by commas.)
      schema:
        type: array
        items:
          type: integer
      style: form
      explode: false
      example: [1, 2, 3]
```

This schema is, of course, correct.

When this schema is documented using a library, it appears as shown below, but I think it is difficult to understand🤔

Because when used as a query parameter, it is actually not an array but a comma-separated value.

![Image](https://github.com/user-attachments/assets/2889c10f-3ae7-40c6-a312-7c4b36fdfc53)
