### ISSUE TITLE
Display the title property for each property in starlight-openapi

### ISSUE THREAD

**Issue by taiseimiyaji** [HiDeoo/starlight-openapi#82]
### Is your feature request related to a problem?

In starlight-openapi, the title property defined for each field in the OpenAPI specification is not currently displayed. This makes it harder for users to grasp the content of the schema. Other tools, like Swagger and Redocly, do display the title, which helps clarify the meaning of each property.

example schema: 
```yaml
        properties: 
          categoryId: 
            title: '部門ID' // Not rendered
            type: string
            description: '部門毎に付与するID'
```

### Describe the solution you'd like

Enable starlight-openapi to show the title property for each property in the OpenAPI specification. Having a user interface similar to Swagger or Redocly that includes these title fields would enhance readability and improve the user experience.

### Describe alternatives you've considered

We considered putting this in the Description, but it is unnatural for an OpenAPI specification.

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands:

> We considered putting this in the Description, but it is unnatural for an OpenAPI specification.

Interesting, for me it's pretty much the opposite and I always use the `description` field and never the `title` one.

If we consider the following schema:

```yaml
name:
  type: string
  title: Name of the animal
  description: A friendly name for the animal.
```

The current rendering would be:

<img width="712" alt="Image" src="https://github.com/user-attachments/assets/4d988ffe-82dc-4f5c-94a2-d4ff250746dc" />

Would a rendering like the following be more helpful and what you would expect?

<img width="716" alt="Image" src="https://github.com/user-attachments/assets/25358161-9f74-4be1-9587-9d23a3948f90" />

As someone who never relies on the `title` field, I prefer to ask first before making any changes.
